### ISSUE TITLE
Please add eye locations for The Blackbeard

### ISSUE THREAD

**Issue by JohnnyBazooka89** [twanvl/sts-googly-mod#3]
This json contains ONLY the eyes that are used for The Blackbeard. (I removed everything else). Please merge them to your file.

[eye-locations.zip](https://github.com/twanvl/sts-googly-mod/files/2621179/eye-locations.zip)

**Comment by twanvl** [comment]
You can now put custom googly eye locations in `googly-eye-locations.json` in any mod (in the same directory as ModTheSpire.json).

**Comment by JohnnyBazooka89** [comment]
Nice! I see you implemented my suggestion from discord. :) I will add this file to my mod instead.
