### ISSUE TITLE
Ghost in a jar is missing googly eyes

### ISSUE THREAD

**Issue by musshorn** [twanvl/sts-googly-mod#7]
Look at these freaky ghost eyes
![image](https://user-images.githubusercontent.com/874740/51967875-909e6380-24c4-11e9-800d-3446bc57fc34.png)
Absolutely terrifying. Something must be done.

**Comment by twanvl** [comment]
You are entirely correct, sir space cat.
I have corrected this grievous error, and uploaded a fixed version to the steam workshop.
